export type Exd = { name: string; muscle: string; sci: string; img: string };
export type DayD = { name: string; exercises: { A: Exd[]; B: Exd[]; C: Exd[] } };

const PFX = "https://images.unsplash.com/";
const SFX = "?w=400&q=80";
const IMGS: Record<string, string> = {
  sq: "photo-1567598508481-65985588e295",
  dl: "photo-1598971639058-fab3c3109a37",
  ub: "photo-1571019613454-1cb2f99b2d8b",
  bk: "photo-1526506118085-60ce8714f8c5",
  co: "photo-1518611012118-696072aa579a",
  rn: "photo-1461896836934-ffe607ba8211",
  gl: "photo-1574680096145-d05b474e2155",
  sh: "photo-1583454155184-870a1f63aebc",
  fx: "photo-1518310383802-640c2de311b2",
  kb: "photo-1607962837359-5e7e89f86776",
};
const ex = (n: string, m: string, k: string, s: string): Exd => ({ name: n, muscle: m, sci: s, img: PFX + (IMGS[k] ?? IMGS.co) + SFX });
type Ov = string | null;
const bld = (name: string, A: Exd[], B: Ov[], C: Ov[]): DayD => ({
  name,
  exercises: {
    A,
    B: A.map((e, i) => ({ ...e, name: B[i] ?? e.name })),
    C: A.map((e, i) => ({ ...e, name: C[i] ?? e.name })),
  },
});

export const PROG_DATA: Record<string, Record<string, Record<number, DayD>>> = {
  w: {
    wl: {
      1: bld("Lower Body Burn",
        [ex("Hip Thrust","Glutes","gl","Peak glute EMG."),ex("Romanian Deadlift","Hamstrings","dl","Eccentric deficit training."),ex("Lateral Lunge","Inner Thighs","sq","Frontal plane balance."),ex("Cable Kickback","Glutes","gl","Isolation prevents atrophy."),ex("Plank","Core","co","Anti-extension spine."),ex("Jump Squat","Quads","sq","24h EPOC trigger.")],
        ["Weighted Hip Thrust","Sumo Deadlift","Curtsy Lunge","RB Kickback","Side Plank","Box Jump"],
        ["Barbell Hip Thrust","Single-leg Deadlift","Jump Lunge","Cable Pull-through","Plank+Reach","Depth Jump"]),
      2: bld("HIIT Cardio",
        [ex("Jump Rope","Cardiovascular","rn","36h EPOC effect."),ex("Burpees","Full Body","ub","Max caloric expenditure."),ex("Mountain Climbers","Core & Cardio","co","Core with cardio."),ex("High Knees","Hip Flexors","rn","Hip activation doubles cardio."),ex("Box Jumps","Explosive Power","rn","Fast-twitch recruitment."),ex("Sprint Intervals","VO2 Max","rn","Pushes cardio ceiling.")],
        ["Double Unders","Weighted Burpees","Plyo Climbers","Fast High Knees","Plyo Jumps","Hill Sprints"],
        ["Speed Rope","Burpee Pull-up","Weighted Climbers","Ladder Drills","Depth Jumps","400m Repeats"]),
      3: bld("Upper Body Tone",
        [ex("Push-up","Chest & Triceps","ub","Progressive push pattern."),ex("Dumbbell Row","Back","bk","Horizontal pull posture."),ex("Shoulder Press","Deltoids","sh","Functional shoulder strength."),ex("Lat Pulldown","Lats","bk","Vertical pull width."),ex("Tricep Dips","Triceps","ub","2/3 of arm size."),ex("Bicep Curl","Biceps","ub","Peak stretch recruitment.")],
        ["Archer Push-up","Barbell Row","Arnold Press","Pull Negative","Diamond Push-up","Hammer Curl"],
        ["Plyo Push-up","Pendlay Row","Push Press","Assisted Pull-up","Ring Dips","Concentration Curl"]),
      4: bld("Full Body Circuit",
        [ex("Goblet Squat","Quads & Glutes","sq","Max caloric burn compound."),ex("Push-up","Chest & Triceps","ub","Preserves muscle deficit."),ex("Dumbbell Row","Back","bk","Push:pull shoulder balance."),ex("Hip Thrust","Glutes","gl","Glute shape during cut."),ex("Plank","Core","co","Core supports compounds."),ex("Jump Rope","Cardio","rn","EPOC closing work.")],
        ["Barbell Squat","Pause Push-up","Cable Row","Weighted Hip Thrust","Side Plank","Battle Ropes"],
        ["Front Squat","Weighted Dips","Pendlay Row","Barbell Hip Thrust","Dragon Flag","Assault Bike"]),
    },
    mb: {
      1: bld("Glutes & Legs",
        [ex("Bulgarian Split Squat","Glutes & Quads","sq","Corrects size asymmetry."),ex("Goblet Squat","Quads & Glutes","sq","Full-depth hypertrophy."),ex("Hip Thrust","Glutes","gl","Progressive overload glutes."),ex("Romanian Deadlift","Hamstrings","dl","Isolates posterior chain."),ex("Leg Press","Quads","sq","Volume without spine load."),ex("Calf Raise","Calves","sq","High-rep lower leg.")],
        ["Barbell Squat","Pause Squat","Weighted Hip Thrust","Sumo Deadlift","Hack Squat","Single-leg Calf"],
        ["Front Squat","Belt Squat","Barbell Hip Thrust","Single-leg Deadlift","Spanish Squat","Donkey Calf"]),
      2: bld("Back & Biceps",
        [ex("Lat Pulldown","Lats","bk","Vertical pull lat width."),ex("Dumbbell Row","Back","bk","Mid-back density."),ex("Cable Row","Mid Back","bk","Constant cable tension."),ex("Face Pull","Rear Delts","sh","Essential shoulder health."),ex("Bicep Curl","Biceps","ub","Peak stretch hypertrophy."),ex("Hammer Curl","Brachialis","ub","Arm thickness neutral grip.")],
        ["Pull Negative","Barbell Row","Seated Row","Rear Delt Fly","Preacher Curl","EZ-bar Curl"],
        ["Pull-up","Pendlay Row","Dead Row","Band Pull-apart","Incline Curl","Reverse Curl"]),
      3: bld("Chest & Triceps",
        [ex("Incline DB Press","Upper Chest","ub","Incline targets upper pec."),ex("Push-up","Chest","ub","High-rep volume."),ex("Cable Fly","Chest","ub","Constant tension isolation."),ex("Shoulder Press","Anterior Delts","sh","Compound shoulder mass."),ex("Tricep Pushdown","Triceps","ub","Lateral head isolation."),ex("Overhead Extension","Triceps","ub","Long-head stretch hypertrophy.")],
        ["Flat Bench Press","Pause Push-up","Pec Dec","Seated DB Press","Skull Crushers","CG Push-up"],
        ["Weighted Dips","Plyo Push-up","Cable Crossover","Push Press","JM Press","Tricep Kickback"]),
      4: bld("Full Body Power",
        [ex("Deadlift","Full Body","dl","Most effective compound."),ex("Barbell Squat","Quads & Glutes","sq","Primary lower compound."),ex("Pull-up","Back & Biceps","bk","Best upper pulling."),ex("Bench Press","Chest & Triceps","ub","Horizontal press strength."),ex("Plank","Core","co","Core caps power day."),ex("Jump Squat","Power","sq","Explosive finisher metabolism.")],
        ["Pause Deadlift","Front Squat","Weighted Pull-up","Incline Press","Ab Wheel","Box Jump"],
        ["Trap Bar DL","Overhead Squat","L-sit Pull-up","CG Bench","Dragon Flag","Depth Jump"]),
    },
    st: {
      1: bld("Lower Power",
        [ex("Barbell Squat","Quads & Core","sq","85%+ neural adaptation."),ex("Romanian Deadlift","Hamstrings","dl","Heavy posterior chain."),ex("Leg Press","Quads","sq","Volume, no spine load."),ex("Hip Thrust","Glutes","gl","Glute strength lockout."),ex("Calf Raise","Calves","sq","Ankle stability load."),ex("Plank","Core","co","Core force transfer.")],
        ["Pause Squat","Stiff-leg DL","Hack Squat","Weighted Hip Thrust","Single-leg Calf","Ab Wheel"],
        ["Competition Squat","Deficit DL","Belt Squat","Barbell Hip Thrust","Loaded Calf","Dragon Flag"]),
      2: bld("Upper Strength",
        [ex("Bench Press","Chest & Triceps","ub","Primary horizontal strength."),ex("Overhead Press","Shoulders","sh","Vertical push strength."),ex("Pull-up","Back & Biceps","bk","Best relative strength."),ex("Dumbbell Row","Back","bk","Corrects imbalances."),ex("Tricep Dips","Triceps","ub","Pressing lockout strength."),ex("Face Pull","Rear Delts","sh","Shoulder health mandatory.")],
        ["Pause Bench","Push Press","Weighted Pull-up","Barbell Row","Weighted Dips","Band Pull-apart"],
        ["Board Press","Jerk","L-sit Pull-up","Pendlay Row","Ring Dips","Rear Delt Row"]),
      3: bld("Full Body Strength",
        [ex("Deadlift","Full Body","dl","King of strength movements."),ex("Front Squat","Quads & Core","sq","Anterior quad strength."),ex("Push Press","Shoulders","sh","Kinetic chain power."),ex("Barbell Row","Back","bk","Balances pressing."),ex("Nordic Curl","Hamstrings","dl","Injury risk reduction."),ex("Farmer Walk","Grip & Core","dl","Real functional strength.")],
        ["Sumo DL","Zercher Squat","Jerk","Pendlay Row","GH Raise","Yoke Walk"],
        ["Deficit DL","Safety Bar Squat","Split Jerk","Weighted Pull-up","Single-leg DL","Atlas Carry"]),
    },
    en: {
      1: bld("Zone 2 Steady",
        [ex("Running Intervals","Cardiovascular","rn","Zone 2 mitochondrial density."),ex("Stair Climber","Glutes & Cardio","gl","Glute aerobic base."),ex("Rowing","Full Body Aerobic","bk","Low-impact full-body."),ex("Jump Rope","Conditioning","rn","High caloric minimal equipment."),ex("Bodyweight Squat","Legs","sq","Maintains muscle mass."),ex("Cool Down Stretch","Flexibility","fx","Reduces DOMS recovery.")],
        ["Tempo Run","Step Mill","Ergometer","Double Unders","Step-up","Hip Flexor Stretch"],
        ["Long Intervals","Weighted Stair","Row Sprints","Speed Rope","Squat Hold","Yoga Flow"]),
      2: bld("Strength Base",
        [ex("Bodyweight Squat","Legs","sq","Maintains mass in cardio."),ex("Push-up","Upper Body","ub","Preserves upper strength."),ex("Dumbbell Row","Back","bk","Prevents posture issues."),ex("Plank","Core Endurance","co","Running foundation."),ex("Hip Thrust","Glutes","gl","Primary running power."),ex("Reverse Lunge","Legs","sq","Prevents gait asymmetry.")],
        ["Goblet Squat","Archer Push-up","Cable Row","Side Plank","Weighted Bridge","Walking Lunge"],
        ["Barbell Squat","Weighted Dips","Barbell Row","Ab Wheel","Barbell Hip Thrust","Jump Lunge"]),
      3: bld("Tempo Intervals",
        [ex("Sprint Intervals","VO2 Max","rn","Pushes aerobic ceiling."),ex("High Knees","Hip Flexors","rn","Improves running economy."),ex("Box Jumps","Explosive Power","rn","Running power output."),ex("Jump Rope","Coordination","rn","Foot strike rhythm."),ex("Mountain Climbers","Core & Cardio","co","Core stability demand."),ex("Cool Down Walk","Recovery","rn","Active lactate clearance.")],
        ["Hill Sprints","Fast Feet","Plyo Jumps","Double Unders","Plyo Push-up","Light Jog"],
        ["400m Repeats","Ladder Drills","Depth Jumps","Speed Rope","Burpees","Stride Outs"]),
      4: bld("Cross Training",
        [ex("Rowing","Full Body Aerobic","bk","Non-impact full-body."),ex("Cycling","Aerobic Base","rn","Quad cardio no impact."),ex("Hip Mobility","Hip Flexibility","fx","Reverses running tightness."),ex("Shoulder Mobility","Shoulders","sh","Maintains running posture."),ex("Core Circuit","Core Endurance","co","Core maintains form."),ex("Foam Rolling","Recovery","co","Reduces soreness.")],
        ["Row Intervals","Bike HIIT","Deep Stretching","Band Shoulder","Plank Complex","Mobility Flow"],
        ["Max Effort Row","Zwift Ride","Full Body Mobility","Shoulder CARs","Dragon Flag","Recovery Yoga"]),
      5: bld("Long Session",
        [ex("Long Run","Aerobic Capacity","rn","Long distance aerobic base."),ex("Plank","Core Endurance","co","Core maintains form."),ex("Glute Bridge","Glutes","gl","Post-run activation."),ex("Hip Flexor Stretch","Flexibility","fx","Long run tightness."),ex("Calf Stretch","Calves","fx","Injury risk reduction."),ex("Breathing Drills","Respiratory","co","Running economy.")],
        ["Progression Run","Side Plank","Single-leg Bridge","Pigeon Pose","Downward Dog","Box Breathing"],
        ["Race Pace Run","Ab Wheel","Weighted Bridge","Full Hip Flow","Hamstring Flow","Apnea Training"]),
    },
    fl: {
      1: bld("Hip & Glute Mobility",
        [ex("Hip Flexor Stretch","Hip Flexors","fx","Reduces anterior tilt."),ex("Pigeon Pose","Glutes & Hips","gl","PNF hip ROM increase."),ex("Glute Bridge","Glutes","gl","Reinforces new ROM."),ex("Figure-4 Stretch","Piriformis","co","Releases deep rotators."),ex("Hip Circle","Hip Joint","gl","Lubricates hip capsule."),ex("Deep Squat Hold","Hip & Ankle","sq","Total lower mobility.")],
        ["Low Lunge","Double Pigeon","Single-leg Bridge","Supine Figure-4","Hip CARs","Squat+Reach"],
        ["Lizard Pose","Advanced Pigeon","Weighted Bridge","Thread Needle","Hip 90/90","ATG Squat"]),
      2: bld("Spine & Thoracic",
        [ex("Cat-Cow","Lumbar Spine","co","Spinal segment mobility."),ex("Thoracic Rotation","Mid-Back","co","Restores rotation loss."),ex("Superman Hold","Erector Spinae","co","Strengthens extensors."),ex("Bird-Dog","Core & Balance","co","Anti-rotation decompression."),ex("Spinal Twist","Thoracic","co","Mobilises full column."),ex("Cobra Stretch","Lumbar","co","Counteracts flexion posture.")],
        ["Thread Needle","World's Greatest","T-spine Opener","Dead Bug","Windmill","Upward Dog"],
        ["Spinal Wave","Full T-Spine Rotation","Back Extension","Hollow Hold","KB Windmill","Wheel Pose"]),
      3: bld("Hamstring & Lower",
        [ex("Standing Hamstring","Hamstrings","co","Posterior chain flexibility."),ex("Seated Forward Fold","Hamstrings & Spine","co","Combined spinal stretch."),ex("Downward Dog","Full Posterior","co","Hamstrings calves spine."),ex("Calf Stretch","Calves & Achilles","fx","Prevents injury risk."),ex("Ankle Rotation","Ankle Joint","sq","Joint mobility safety."),ex("Supine Hip Flexion","Hamstrings","gl","Gravity assists lengthening.")],
        ["PNF Hamstring","Straddle Fold","Three-leg Dog","Soleus Stretch","Ankle CARs","AIS Hamstring"],
        ["Active Straight Leg","Yoga Splits Prep","Full Downward Dog","Weighted Calf Stretch","Ankle Mobility","Eccentric Hamstring"]),
      4: bld("Shoulder & Upper",
        [ex("Shoulder Cross Stretch","Posterior Delt","sh","Reduces chronic tightness."),ex("Thread the Needle","Thoracic & Shoulder","co","Rotation shoulder opening."),ex("Wall Angels","Shoulder Stability","sh","Scapular movement pattern."),ex("Doorway Stretch","Chest & Delt","ub","Opens anterior shoulder."),ex("Neck Rolls","Cervical Spine","co","Releases upper trap."),ex("Wrist Circles","Wrist","ub","Maintains pressing mobility.")],
        ["Shoulder CARs","Thoracic Open","Band Pull-apart","PNF Chest","Upper Trap","Wrist Flow"],
        ["Full Shoulder Orbit","Shoulder Dislocate","Scapular Push-up","Sleeper Stretch","Cervical Retraction","Wrist Supination"]),
      5: bld("Full Body Yoga",
        [ex("Sun Salutation","Full Body","fx","Warms every joint."),ex("Warrior I","Hips & Shoulders","gl","Opens hips proprioception."),ex("Warrior II","Hips & Legs","gl","Stability inner thigh."),ex("Pigeon Pose","Glutes & Hips","gl","Deepest hip opener."),ex("Child's Pose","Spine & Hips","co","Passive decompression."),ex("Savasana","Full Body","fx","Nervous system integration.")],
        ["Vinyasa Flow","Warrior III","Extended Side Angle","Thread Needle","Legs Up Wall","Yoga Nidra"],
        ["Ashtanga Primary","Half Moon","Scorpion Prep","Full Lotus","Restorative Flow","Deep Savasana"]),
    },
    br: {
      1: bld("Strength Circuit A",
        [ex("Deadlift","Full Body","dl","Highest muscle recruitment."),ex("Goblet Squat","Quads & Glutes","sq","Front-loaded core too."),ex("Push-up","Chest & Triceps","ub","Preserves muscle recomp."),ex("Dumbbell Row","Back","bk","Balanced upper development."),ex("Plank","Core","co","Core transfers compounds."),ex("Hip Thrust","Glutes","gl","Glute preservation recomp.")],
        ["Romanian DL","Barbell Squat","Pause Push-up","Cable Row","Side Plank","Weighted Hip Thrust"],
        ["Sumo DL","Front Squat","Weighted Dips","Pendlay Row","Dragon Flag","Barbell Hip Thrust"]),
      2: bld("HIIT Conditioning",
        [ex("Jump Rope","Cardiovascular","rn","EPOC muscle preservation."),ex("Burpees","Full Body","ub","Max caloric expenditure."),ex("Mountain Climbers","Core & Cardio","co","Core with conditioning."),ex("High Knees","Hip Flexors","rn","Hip drive mechanisms."),ex("Box Jumps","Explosive Power","rn","Fast-twitch preservation."),ex("Sprint Intervals","VO2 Max","rn","Fat oxidation pathways.")],
        ["Double Unders","Weighted Burpees","Plyo Climbers","Fast Feet","Plyo Jumps","Hill Sprints"],
        ["Speed Rope","Burpee Pull-up","Weighted Climbers","Ladder Drills","Depth Jumps","400m Repeats"]),
      3: bld("Strength Circuit B",
        [ex("Romanian Deadlift","Hamstrings","dl","Eccentric posterior preservation."),ex("Dumbbell Press","Chest","ub","Progressive overload recomp."),ex("Cable Row","Back","bk","Constant tension isolation."),ex("Bulgarian Split Squat","Glutes & Quads","sq","Best single-leg exercise."),ex("Shoulder Press","Deltoids","sh","Overhead builds width."),ex("Jump Squat","Power","sq","Explosive EPOC finisher.")],
        ["Stiff-leg DL","Incline Press","Barbell Row","Walking Lunge","Arnold Press","Box Jump"],
        ["Single-leg DL","Push Press","Pendlay Row","Jump Lunge","Push Jerk","Depth Jump"]),
      4: bld("HIIT + Core",
        [ex("Battle Ropes","Cardiovascular","ub","High-intensity conditioning."),ex("Plank Hold","Core","co","Anti-extension development."),ex("Russian Twist","Rotational Core","co","Obliques rotational power."),ex("Mountain Climbers","Core & Cardio","co","Core sustained cardio."),ex("Jump Squat","Legs & Power","sq","Lower body EPOC."),ex("Bicycle Crunch","Core","co","All four core groups.")],
        ["Slam Ball","Ab Wheel","Weighted Russian Twist","Plyo Push-up","Box Jump","Hanging Knee Raise"],
        ["KB Swing","Dragon Flag","Pallof Press","Burpee","Depth Jump","Toes-to-Bar"]),
    },
  },
  m: {
    wl: {
      1: bld("Lower Body Power",
        [ex("Barbell Squat","Quads & Core","sq","Maximum lower caloric burn."),ex("Romanian Deadlift","Hamstrings","dl","Posterior preserves muscle."),ex("Leg Press","Quads","sq","Volume no spine load."),ex("Kettlebell Swing","Posterior Chain","kb","Hip hinge metabolic."),ex("Box Jump","Explosive Power","rn","Fast-twitch deficit."),ex("Calf Raise","Calves","sq","Lower leg maintenance.")],
        ["Pause Squat","Sumo DL","Hack Squat","Weighted KB Swing","Depth Box Jump","Single-leg Calf"],
        ["Front Squat","Trap Bar DL","Belt Squat","Double KB Swing","Reactive Jump","Loaded Calf"]),
      2: bld("Upper + Cardio",
        [ex("Pull-up","Back & Biceps","bk","Upper body preservation."),ex("Bench Press","Chest & Triceps","ub","Chest mass in deficit."),ex("Dumbbell Row","Back","bk","Corrects imbalances."),ex("Battle Ropes","Cardiovascular","ub","EPOC no muscle loss."),ex("Burpees","Full Body","ub","Max caloric expenditure."),ex("Mountain Climbers","Core & Cardio","co","Core cardiovascular.")],
        ["Weighted Pull-up","Pause Bench","Barbell Row","Assault Bike","Weighted Burpees","Ab Wheel"],
        ["L-sit Pull-up","Board Press","Pendlay Row","Max Effort Row","Burpee Pull-up","Dragon Flag"]),
      3: bld("Full Body Metabolic",
        [ex("Deadlift","Full Body","dl","Hormonal fat-burning response."),ex("Push-up","Chest & Triceps","ub","Accessory mass preservation."),ex("Kettlebell Swing","Posterior Chain","kb","Hip power metabolic."),ex("Sled Push","Full Body Power","sq","High intensity no fatigue."),ex("Jump Rope","Cardio","rn","Sustained EPOC intervals."),ex("Plank","Core","co","Safe metabolic session.")],
        ["Pause DL","Plyo Push-up","Double KB Swing","Sled Sprint","Double Unders","Side Plank"],
        ["Sumo DL","Weighted Dips","KB Snatch","Heavy Sled","Assault Bike","Dragon Flag"]),
      4: bld("HIIT + Core",
        [ex("Sprint Intervals","VO2 Max","rn","Testosterone fat loss."),ex("Burpees","Full Body","ub","Total-body caloric burn."),ex("Mountain Climbers","Core & Cardio","co","Core conditioning."),ex("Plank","Core Stability","co","Anti-extension compounds."),ex("Hanging Knee Raise","Core","co","Functional abdominal."),ex("Russian Twist","Rotational Core","co","Oblique rotation strength.")],
        ["Hill Sprints","Weighted Burpees","Bicycle Crunch","Ab Wheel","Hanging Leg Raise","Pallof Press"],
        ["400m Repeats","Burpee Pull-up","Toes to Bar","Dragon Flag","Weighted Crunch","Landmine Twist"]),
    },
    mb: {
      1: bld("Chest & Triceps",
        [ex("Bench Press","Chest & Triceps","ub","8-12 reps optimal hypertrophy."),ex("Incline DB Press","Upper Chest","ub","Varied angle pec."),ex("Cable Fly","Chest","ub","Constant tension isolation."),ex("Tricep Dips","Triceps","ub","2/3 of arm size."),ex("Skull Crushers","Triceps Long Head","ub","Long head complete development."),ex("Push-up","Chest Finisher","ub","Metabolic stress hypertrophy.")],
        ["Pause Bench","Weighted Incline","Pec Dec","Weighted Dips","CG Bench","Ring Push-up"],
        ["Board Press","Heavy Incline","Cable Crossover","Belt Dips","JM Press","Plyo Push-up"]),
      2: bld("Back & Biceps",
        [ex("Pull-up","Lats & Biceps","bk","Non-negotiable lat width."),ex("Barbell Row","Back Thickness","bk","Heavy rows V-taper."),ex("Lat Pulldown","Lats","bk","Volume post pull-ups."),ex("Cable Row","Mid Back","bk","Superior tension isolation."),ex("Bicep Curl","Biceps","ub","Peak stretch recruitment."),ex("Hammer Curl","Brachialis","ub","Arm thickness grip.")],
        ["Weighted Pull-up","Pendlay Row","CG Pulldown","Seated Row","Preacher Curl","EZ-bar Curl"],
        ["L-sit Pull-up","Yates Row","Wide-grip Pulldown","Rope Row","Incline Curl","Drag Curl"]),
      3: bld("Legs",
        [ex("Barbell Squat","Quads & Core","sq","King of leg mass."),ex("Leg Press","Quads","sq","Controlled post-squat volume."),ex("Romanian Deadlift","Hamstrings","dl","Eccentric posterior development."),ex("Leg Curl","Hamstrings","dl","Full isolation development."),ex("Leg Extension","Quads","sq","Terminal quad sweep."),ex("Calf Raise","Gastrocnemius","sq","High-rep calf volume.")],
        ["Pause Squat","Hack Squat","Stiff-leg DL","Nordic Curl","Sissy Squat","Seated Calf"],
        ["Front Squat","Belt Squat","Snatch DL","GH Raise","Spanish Squat","Donkey Calf"]),
      4: bld("Shoulders",
        [ex("Overhead Press","All Delt Heads","sh","Compound before isolation."),ex("Lateral Raise","Lateral Delt","sh","Capped shoulder look."),ex("Front Raise","Anterior Delt","sh","Frontal shoulder development."),ex("Face Pull","Rear Delt","sh","Most important health."),ex("Shrug","Upper Traps","bk","Frames neck upper back."),ex("Arnold Press","All Delt Heads","sh","Recruits all three heads.")],
        ["Push Press","Cable Lateral","DB Front Raise","Band Pull-apart","Heavy Shrug","DB Arnold"],
        ["Jerk","Plate Lateral","L-Raise","Rear Delt Row","Trap Bar Shrug","1-arm Arnold"]),
      5: bld("Arms + Core",
        [ex("Preacher Curl","Biceps Peak","ub","Locked elbow peak."),ex("Tricep Pushdown","Triceps Lateral Head","ub","Cable lateral isolation."),ex("Hammer Curl","Brachialis","ub","Pushes bicep peak."),ex("Plank","Core","co","Core balanced session."),ex("Ab Wheel","Full Anterior Chain","co","Full wrists-to-hips."),ex("Hanging Knee Raise","Lower Abs","co","Lower ab development.")],
        ["Incline Curl","CG Bench","Cable Curl","Ab Wheel","Hanging Leg Raise","Bicycle Crunch"],
        ["Drag Curl","Floor Press","Spider Curl","Dragon Flag","Toes to Bar","Pallof Press"]),
    },
    st: {
      1: bld("Squat Day",
        [ex("Barbell Squat","Quads & Core","sq","85%+ neural adaptation."),ex("Front Squat","Quads & Core","sq","Anterior quad dominance."),ex("Leg Press","Quads","sq","Accessory no spine."),ex("Romanian Deadlift","Hamstrings","dl","Posterior accessory strength."),ex("Calf Raise","Calves","sq","Ankle stability loads."),ex("Plank","Core","co","Bracing transfers squats.")],
        ["Pause Squat","Zercher Squat","Hack Squat","Stiff DL","Single-leg Calf","Ab Wheel"],
        ["Competition Squat","Safety Bar Squat","Belt Squat","Deficit DL","Loaded Calf","Dragon Flag"]),
      2: bld("Press Day",
        [ex("Bench Press","Chest & Triceps","ub","Primary horizontal strength."),ex("Overhead Press","Shoulders","sh","Functional overhead capacity."),ex("Incline Press","Upper Chest","ub","Complete chest strength."),ex("Tricep Dips","Triceps","ub","Lockout all pressing."),ex("Push-up","Chest Endurance","ub","Shoulder accessory volume."),ex("Face Pull","Rear Delt","sh","Mandatory presser health.")],
        ["Pause Bench","Push Press","Floor Press","Weighted Dips","Ring Push-up","Band Pull"],
        ["Board Press","Jerk","CG Bench","Belt Dips","Plyo Push-up","Rear Delt Row"]),
      3: bld("Hinge Day",
        [ex("Deadlift","Full Body","dl","King of strength."),ex("Romanian Deadlift","Hamstrings","dl","Eccentric end range."),ex("Good Morning","Erector & Hamstrings","dl","Deadlift alignment."),ex("Barbell Row","Back Thickness","bk","Balances pressing."),ex("Pull-up","Lats & Biceps","bk","Vertical upper back."),ex("Nordic Curl","Hamstrings","dl","Hamstring injury prevention.")],
        ["Sumo DL","Snatch DL","Stiff DL","Pendlay Row","Weighted Pull-up","GH Raise"],
        ["Deficit DL","Pause DL","45° Back Ext","Yates Row","L-sit Pull-up","Single-leg RDL"]),
      4: bld("Power Day",
        [ex("Power Clean","Full Body Explosive","rn","Rate of force development."),ex("Push Press","Shoulders & Legs","sh","Kinetic chain power."),ex("Box Jump","Explosive Legs","rn","Fast-twitch efficiency."),ex("Farmer Walk","Grip & Core","dl","Real functional strength."),ex("Battle Ropes","Conditioning","ub","Explosive conditioning."),ex("Plank","Core Power","co","Core power transfer.")],
        ["Hang Clean","Push Jerk","Depth Jump","Double KB Carry","Slam Ball","Ab Wheel"],
        ["Full Clean","Split Jerk","Reactive Jump","Yoke Walk","Heavy Slam Ball","Dragon Flag"]),
    },
    en: {
      1: bld("Aerobic Base",
        [ex("Long Run","Aerobic Capacity","rn","Zone 2 mitochondrial density."),ex("Pace Intervals","Lactate Threshold","rn","80% pushes threshold."),ex("Hill Sprints","Power Endurance","rn","Uphill without injury."),ex("Hip Flexor Stretch","Hip Flexibility","fx","Running tightens flexors."),ex("Calf Stretch","Achilles","fx","Prevents plantar fasciitis."),ex("Foam Roll","Recovery","co","Accelerates recovery.")],
        ["Progression Run","LT Intervals","Weighted Hill","Hip CARs","Soleus Stretch","Mobility Flow"],
        ["Race Pace Run","VO2 Intervals","Sprint Hill","Full Hip Flow","Eccentric Calf","Deep Tissue Roll"]),
      2: bld("Strength Maintenance",
        [ex("Barbell Squat","Legs","sq","Heavy squats preserve mass."),ex("Bench Press","Chest","ub","Upper body through endurance."),ex("Pull-up","Back","bk","Non-negotiable retention."),ex("Plank","Core Endurance","co","Running performance foundation."),ex("Romanian Deadlift","Posterior Chain","dl","Prevents running compensations."),ex("Overhead Press","Shoulders","sh","Arm drive requires shoulders.")],
        ["Pause Squat","Weighted Dips","Weighted Pull-up","Ab Wheel","Stiff DL","Push Press"],
        ["Front Squat","Ring Dips","L-sit Pull-up","Dragon Flag","Trap Bar DL","Jerk"]),
      3: bld("Tempo & Intervals",
        [ex("Tempo Run","Lactate Threshold","rn","85% raises threshold."),ex("Sprint Intervals","VO2 Max","rn","Max effort VO2 ceiling."),ex("Box Jumps","Explosive Power","rn","Plyometrics improve economy."),ex("Battle Ropes","Upper Body Cardio","ub","Upper cardio conditioning."),ex("Jump Rope","Coordination","rn","Foot strike rhythm."),ex("Mountain Climbers","Core & Cardio","co","Core cardio demand.")],
        ["LT Tempo","Max Sprints","Depth Jumps","Assault Bike","Double Unders","Burpees"],
        ["VO2 Tempo","400m Repeats","Reactive Jumps","Max Effort Row","Speed Rope","Weighted Burpees"]),
      4: bld("Cross Training",
        [ex("Rowing","Full Body Aerobic","bk","Non-impact aerobic."),ex("Cycling","Aerobic Base","rn","Quad cardio no impact."),ex("Swimming","Full Body","ub","Non-impact recovery."),ex("Assault Bike","Max Output","rn","Arms legs max demand."),ex("Stair Climber","Glutes & Cardio","gl","Lower body glute endurance."),ex("Core Circuit","Core Endurance","co","Core form in fatigue.")],
        ["Row Intervals","Bike Race","Swim Intervals","Max Assault","Weighted Step","Plank Complex"],
        ["Max Row","Criterium Ride","Open Water","Assault Max","Loaded Stair","Dragon Flag"]),
      5: bld("Long Session",
        [ex("Long Run","Aerobic Capacity","rn","Distance psychological endurance."),ex("Walk Intervals","Active Recovery","rn","Walk breaks manage lactate."),ex("Hip Mobility","Hip Flexibility","fx","Long runs stiffen hips."),ex("Quad Stretch","Quad Flexibility","fx","Prevents knee tracking."),ex("Shoulder Mobility","Upper Body","sh","Arm drive long runs."),ex("Breathing Drills","Respiratory","co","Diaphragmatic efficiency.")],
        ["Extended Run","Fast Walk","Hip CARs","PNF Quad","Shoulder Flow","Box Breathing"],
        ["Race Simulation","Active Recovery Run","Full Hip Flow","AIS Quad","Full Shoulder CARs","Apnea Training"]),
    },
    fl: {
      1: bld("Hip Flexors & Glutes",
        [ex("Hip Circle","Hip Joint","gl","Lubricates hip capsule."),ex("Pigeon Pose","Glutes & Rotators","gl","Deep hip piriformis."),ex("Frog Stretch","Adductors & Hips","gl","Wide groin opens hip."),ex("Glute Bridge","Glute Activation","gl","Post-stretch reinforces ROM."),ex("Lateral Hip Stretch","IT Band","gl","Releases athletic tightness."),ex("Deep Squat Hold","Hip & Ankle","sq","Total lower mobility.")],
        ["Hip CARs","Double Pigeon","Wide Frog","Single-leg Bridge","IT Band Cross","ATG Squat"],
        ["Hip 90/90","Advanced Pigeon","Horse Stance","Weighted Bridge","Hip Rotator CARs","Loaded ATG"]),
      2: bld("Thoracic & Shoulders",
        [ex("Thoracic Rotation","Mid-Back","co","Restores pressing rotation."),ex("Wall Angels","Scapular Mobility","sh","Correct scapular move."),ex("Shoulder Pass-through","Full Shoulder ROM","sh","Assesses flexibility."),ex("Cat-Cow","Spinal Mobility","co","Rhythmic spinal flexion."),ex("Thread the Needle","Thoracic Rotation","co","Mid-back not lumbar."),ex("Doorway Stretch","Pec & Delt","ub","Opens anterior shoulder.")],
        ["T-spine CARs","Band Wall Angels","Barbell Pass","Spinal Wave","Twin Needle","PNF Chest"],
        ["Full Rotation CARs","Shoulder Dislocate","Stick Overhead","Full Spinal Wave","Needle Flow","Rack Chest"]),
      3: bld("Ankle & Knee",
        [ex("Ankle Circles","Ankle Dorsiflexion","sq","Restores squat ROM."),ex("Knee Hugs","Hip & Knee Flexion","sq","Sagittal plane mobility."),ex("Calf Stretch","Gastrocnemius","fx","Ankle range of motion."),ex("Quad Stretch","Quad & Hip Flexor","sq","Reduces pelvic tilt."),ex("Figure-4 Stretch","Piriformis","co","Releases sciatic irritation."),ex("Lateral Lunge","Adductors","sq","Dynamic inner thigh.")],
        ["Ankle CARs","90/90 Knee","Eccentric Calf","PNF Quad","Hip Figure-4","Deep Lateral Lunge"],
        ["Ankle Mobility Drill","Knee CARs","Loaded Calf Stretch","Contract-Relax Quad","Pigeon Figure-4","Active Lateral Lunge"]),
      4: bld("Full Lower Body Flow",
        [ex("RDL Stretch","Hamstrings","dl","Controlled hinge mobility."),ex("Hip Hinge Drill","Hip Flexors","gl","Correct hip patterns."),ex("Hamstring Sweep","Hamstrings","co","Dynamic posterior chain."),ex("Pigeon Pose","Glutes","gl","Gold standard external."),ex("Hip Flexor Lunge","Hip Flexors","gl","Deep functional lunge."),ex("Child's Pose","Spine & Hips","co","Passive decompression.")],
        ["Loaded RDL Stretch","Hip Hinge Flow","PNF Hamstring","Pigeon+Rotation","Low Lunge Flow","Extended Child's Pose"],
        ["Barbell RDL Stretch","Hip Hinge Complex","AIS Hamstring","Pigeon+Bind","Lizard Lunge","Yoga Block Child's Pose"]),
      5: bld("Dynamic Activation",
        [ex("Leg Swings","Hip Flexion","gl","Primes hip flexors."),ex("Arm Circles","Shoulder Joint","sh","Warms rotator cuff."),ex("Hip Rotations","Hip Joint","gl","Warms hip capsule."),ex("High Knees","Hip Flexors & Cardio","rn","Dynamic hip cardio."),ex("Butt Kicks","Quad & Hamstring","rn","Dynamic hamstring warm."),ex("Dynamic Lunge","Hips & Legs","sq","Lower body priming.")],
        ["Lateral Leg Swings","Large Arm Circles","Hip Orbit","Fast High Knees","Explosive Butt Kicks","Walking Lunge"],
        ["Multi-plane Leg Swings","Shoulder CARs","Hip 3D Flow","Knee Drive","Hamstring Kick","Jump Lunge"]),
    },
    br: {
      1: bld("Upper Push Power",
        [ex("Bench Press","Chest & Triceps","ub","Compound strength muscle."),ex("Overhead Press","Shoulders","sh","Functional shoulder mass."),ex("Incline DB Press","Upper Chest","ub","Complete upper hypertrophy."),ex("Push-up","Chest Finisher","ub","Volume no joint stress."),ex("Tricep Dips","Triceps","ub","Arm mass lockout."),ex("Battle Ropes","Conditioning","ub","Upper HIIT metabolic.")],
        ["Pause Bench","Push Press","Weighted Incline","Ring Push-up","Weighted Dips","Assault Bike"],
        ["Board Press","Jerk","Heavy Incline","Plyo Push-up","Belt Dips","Max Effort Row"]),
      2: bld("Lower Body Strength",
        [ex("Barbell Squat","Quads & Glutes","sq","Largest stimulus recomp."),ex("Deadlift","Full Body","dl","Maximum muscle recomp."),ex("Romanian Deadlift","Hamstrings","dl","Posterior chain isolation."),ex("Leg Press","Quads","sq","Additional quad volume."),ex("Kettlebell Swing","Hip Power & Cardio","kb","Explosive hip conditioning."),ex("Box Jump","Explosive Power","rn","Fast-twitch preservation.")],
        ["Pause Squat","Sumo DL","Stiff DL","Hack Squat","Double KB Swing","Depth Jump"],
        ["Front Squat","Trap Bar DL","Single-leg DL","Belt Squat","KB Snatch","Reactive Jump"]),
      3: bld("Metabolic HIIT",
        [ex("Sprint Intervals","VO2 Max & Fat Burn","rn","36h EPOC post-session."),ex("Burpees","Full Body Metcon","ub","Highest caloric bodyweight."),ex("Battle Ropes","Upper Body Cardio","ub","Sustained upper cardio."),ex("Mountain Climbers","Core & Cardio","co","Core in conditioning."),ex("Sled Push","Full Body Power","sq","High intensity functional."),ex("Jump Rope","Cardio Finisher","rn","Compact calorie burn.")],
        ["Hill Sprints","Weighted Burpees","Assault Bike","Burpee to Pull-up","Heavy Sled","Double Unders"],
        ["400m Repeats","Burpee Complex","Max Row","Toes to Bar","Prowler Push","Speed Rope"]),
      4: bld("Upper Pull + Core",
        [ex("Pull-up","Back & Biceps","bk","Best upper pulling."),ex("Barbell Row","Back Thickness","bk","Mid-back mass."),ex("Cable Row","Back","bk","Cable constant tension."),ex("Plank","Core Stability","co","Anti-extension complete."),ex("Hanging Knee Raise","Lower Abs","co","Hanging lower ab."),ex("Russian Twist","Rotational Core","co","Oblique rotational strength.")],
        ["Weighted Pull-up","Pendlay Row","Seated Row","Ab Wheel","Hanging Leg Raise","Pallof Press"],
        ["L-sit Pull-up","Yates Row","Rope Row","Dragon Flag","Toes to Bar","Landmine Twist"]),
    },
  },
};

export const SLUG_MAP: Record<string, string> = {
  wl: "wl", mb: "mb", st: "st", en: "en", fl: "fl", br: "br",
};
